---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Пользователь должен иметь возможность зарегистрироваться на сайте магазина
  - Пользователь должен иметь возможность авторизоваться на сайте магазина
  - Пользователь может удалить товар из корзины
  - Пользователь может оформить заказ с переходом на страницу оплаты
