---
functional
  - требование 3
  - требование 4
  - требование 8
  - требование 9
non-functional
  - требование 2
  - требование 5
  - требование 7
  - требование 6
  - требование 10
implicit
  - требование 1
  - Пользователь должен иметь возможность зарегистрироваться на сайте магазина
  - Пользователь должен иметь возможность авторизоваться на сайте магазина
  - Пользователь может удалить товар из корзины
  - Пользователь может оформить заказ с переходом на страницу оплаты
